---
apiVersion: "eks-anywhere.amazon.com/v1"
kind: vSphereUser
spec:
  username:      "eksa"                # optional, default eksa
  group:         "EKSAUsers"        # optional, default EKSAUsers
  globalRole:    "EKSAGlobalRole"      # optional, default EKSAGlobalRole
  userRole:      "EKSAUserRole"          # optional, default EKSAUserRole
  adminRole:     "EKSACloudAdminRole"    # optional, default EKSACloudAdminRole
  datacenter:    "kubecuddle"
  vSphereDomain: "vsphere.kubernerdes.lab"  # this should be the domain used when you login, e.g. YourUsername@vsphere.local
  connection:
    server:      "https://vsphere.kubernerdes.lab"
    insecure:    true 
  objects:
    networks:
      - !!str    "/kubecuddle/network/DSwitch-VM-Network"
    datastores:
      - !!str    "/kubecuddle/datastore/NVMe-1TB"
    resourcePools:
      - !!str    "/kubecuddle/host/Kubernerdes" # I do not use a ResourcePool for my Environment, therefore set it to the clusterName
    folders:
      - !!str    "/kubecuddle/vm/Kubernerdes"
    templates:
      - !!str    "/kubecuddle/vm/Kubernerdes"

